fix indentation

diff --git a/argocd-backup-s3/templates/cronjob.yaml b/argocd-backup-s3/templates/cronjob.yaml
--- a/argocd-backup-s3/templates/cronjob.yaml
+++ b/argocd-backup-s3/templates/cronjob.yaml
@@ -33,10 +33,10 @@ spec:
                 - |
                   # ----------- ENV VAR CHECKS -----------
                   for var in ARGOCD_SERVER ARGOCD_ADMIN_PASSWORD S3_BUCKET_NAME S3_UPLOAD_PREFIX; do
-                  if [ -z "${!var}" ]; then
-                    echo "ERROR: Env Var '$var' is not set. Aborting."
-                    exit 1
-                  fi
+                    if [ -z "${!var}" ]; then
+                      echo "ERROR: Env Var '$var' is not set. Aborting."
+                      exit 1
+                    fi
                   done
 
                   # ----------- AWS CLI CHECKS -----------
@@ -50,8 +50,8 @@ spec:
                   # ----------- LOGIN TO ARGOCD -----------
                   echo "Logging in to ArgoCD Server: ${ARGOCD_SERVER}"
                   argocd login ${ARGOCD_SERVER} --username admin --password ${ARGOCD_ADMIN_PASSWORD} --plaintext || {
-                      echo "ERROR: ArgoCD login failed. Make sure to use admin account password!"
-                      exit 1
+                    echo "ERROR: ArgoCD login failed. Make sure to use admin account password!"
+                    exit 1
                   }
                   argocd context
                   argocd account get-user-info
